# Arthimetic Operator

In [15]:
import numpy as np

In [16]:
arr=np.array([1,2,3,4,5])
var2=np.array([2,3,4,5,6])
add=arr+var2
print(add)

[ 3  5  7  9 11]


In [17]:
arr=np.array([[1,2,3,4],[5,6,7,8]])   #Two dimension 
arr1=np.array([[1,2,3,4],[5,6,7,8]])
add=arr+arr1
print(add)

[[ 2  4  6  8]
 [10 12 14 16]]


In [18]:
arr=np.array([[[1,2,3,4]]])   #Three dimension 
arr1=np.array([[[1,2,3,4]]])
add=arr+arr1
print(add)

[[[2 4 6 8]]]


# Athimetic operator with numpy

In [19]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
add=np.add(a,b)
print(add)

sub=np.subtract(a,b)
print(f"sub is:{sub}")

multi=np.multiply(a,b)
print(f"multi is:{multi}")

divide=np.divide(a,b)
print(f"divide is:{divide}")

[ 6  8 10 12]
sub is:[-4 -4 -4 -4]
multi is:[ 5 12 21 32]
divide is:[0.2        0.33333333 0.42857143 0.5       ]


Arthimetic operation with scalar

In [21]:
arr=np.array([1,2,3,4,5])   
add=arr+3
print(f"add is:{add}")
sub=arr-3
print(f"sub is:{sub}")
multi=arr*3
print(f"multi is:{multi}")
module=arr%3
print(f"module is:{module}")
power=arr**2
print(f"power is:{power}")

add is:[4 5 6 7 8]
sub is:[-2 -1  0  1  2]
multi is:[ 3  6  9 12 15]
module is:[1 2 0 1 2]
power is:[ 1  4  9 16 25]


Arthimetic Function

In [22]:
# Arthimetic Function
arr=np.array([1,2,3,4,5,6])
a=np.max(arr)
print(arr)
print(f"Maximim number in this array is:{a}")

[1 2 3 4 5 6]
Maximim number in this array is:6


In [23]:
b=np.min(arr)
print(f"minimun number in this array is:{b}")

minimun number in this array is:1


In [24]:
#Tell us about index of min or max value
c=np.argmax(arr) 
print(c)
d=np.argmin(arr)
print(d)

5
0


In [25]:
square=np.array([4,9,16])
e=np.sqrt(square)
print(f"Square root of array is:{e}")

Square root of array is:[2. 3. 4.]


In [26]:
arr2D=np.array([[1,2,3,4],[3,4,5,6]])
print("2D Array:\n",arr2D)
print("\nmax:",np.max(arr2D))
print("min:",np.min(arr2D))
#axis=0 this is for coloum and axis=1 is for row
print("\ncoloum wise check")
print("max coloum wise:",np.max(arr2D,axis=0))
print("min coloum wise:",np.min(arr2D,axis=0))
print("\nrow wise check")
print("min row wise:",np.min(arr2D,axis=1))
print("max row wise",np.max(arr2D,axis=1))


2D Array:
 [[1 2 3 4]
 [3 4 5 6]]

max: 6
min: 1

coloum wise check
max coloum wise: [3 4 5 6]
min coloum wise: [1 2 3 4]

row wise check
min row wise: [1 3]
max row wise [4 6]


In [27]:
angle=np.array([45,60,90])
print(np.sin(angle))
print(np.cos(angle))

[ 0.85090352 -0.30481062  0.89399666]
[ 0.52532199 -0.95241298 -0.44807362]


In [28]:
cumsum=np.array([1,2,3,4])
print(np.cumsum(cumsum))

[ 1  3  6 10]


# Shape

In [29]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(arr.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


Reshape

In [30]:
arr1=np.array([1,2,3,4,5,6,7,8])
x=arr1.reshape(4,2)
print(x)
print(x.ndim)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
2


In [31]:
arr1=np.array([1,2,3,4,5,6,7,8])
x=arr1.reshape(1,1,8)
print(x)
print(x.ndim)

[[[1 2 3 4 5 6 7 8]]]
3


In [32]:
#change into one dimension
one=x.reshape(-1)
print(one)

[1 2 3 4 5 6 7 8]
