Some basic codes for numpy are given:

In [51]:
import numpy as np

x=np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


# Zeros

In [52]:
x=np.zeros((2,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [53]:
print(x.shape)

(2, 3)


In [54]:
x=np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [55]:
x=np.zeros((3,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Ones 

In [56]:
ones_arr=np.ones(5)
print(ones_arr)

[1. 1. 1. 1. 1.]


In [57]:
twoD_ones_arr=np.ones((2,3))
print(twoD_ones_arr)

[[1. 1. 1.]
 [1. 1. 1.]]


# Empty

In [58]:
arr_em=np.empty(4)#empty function give us previous result
print(arr_em)

[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.69761995e-312]


# Range

In [59]:
arr_ran=np.arange(4)#Range Function
print(arr_ran)

[0 1 2 3]


In [60]:
arr=np.arange(1,10,2)#Range Function with start, stop and step
print(arr)

[1 3 5 7 9]


# Diginal

In [61]:
Diginal=np.eye(3)#Identity Matrix
print(Diginal)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Linespace

In [63]:
arr_lin=np.linspace(1,10,num=5)#linspace function with start, stop and number of elements
print(arr_lin)

[ 1.    3.25  5.5   7.75 10.  ]
