# Broadcosting

`Why broadcosting?`
- Broadcosting is a method used in cost accounting to allocate costs across multiple products or services
- in a way that reflects their relative consumption of resources. It helps businesses understand the overall cost structure and profitability of their offerings.
- This approach is particularly useful for companies with diverse product lines or services, as it allows them to make informed decisions about pricing, resource allocation, and profitability analysis.

In [2]:
import numpy as np
var1=np.array([1,2,3,4])
print(var1.shape)
var2=np.array([1,2,3])
print(var2.shape)

(4,)
(3,)


In [3]:
# print(var1+var2)
#when we add these two an error shows because the shapes are not compatible
#we can use broadcasting to add these two arrays

In [4]:
#we also solve this error as
a=np.array([1,2,3,4])
b=np.array([[1],[2],[3]])#we can use any dimension
print(a+b)

[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


In [5]:
b=np.array([[1],[2],[3]])
c=np.array([[1,2],[3,4],[5,6]])
print(c.shape)
print(c)

(3, 2)
[[1 2]
 [3 4]
 [5 6]]


In [6]:
print(b+c)

[[2 3]
 [5 6]
 [8 9]]
