# Data Type

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5,6,7,8])
print(F"data type is: {arr.dtype}")

data type is: int32


In [3]:
arr=np.array([1.4,2.1,0.3,4.1,5.9])
print(F"data type is: {arr.dtype}")

data type is: float64


In [4]:
arr=np.array(["Ali","Ahmad","Hassan"])
print(F"data type is: {arr.dtype}")

data type is: <U6


Data type with array

In [5]:
arr=np.array([1,2,3,4,5],dtype=np.float64)
print(arr,arr.dtype)

arr=np.array([1,2,3,4,5],dtype=np.int64)
print(arr,arr.dtype)

[1. 2. 3. 4. 5.] float64
[1 2 3 4 5] int64


In [6]:
arr=np.array([1,2,3,4,5],dtype="i")
print(arr,arr.dtype)

arr1=np.array([1,2,3,4,5],dtype="f")
print(arr1,arr1.dtype)

arr2=np.array([1,2,3,4,5],dtype="S")#string
print(arr2,arr2.dtype)

arr3=np.array([1,2,3,4,5],dtype="b")#boolian
print(arr3,arr3.dtype)



[1 2 3 4 5] int32
[1. 2. 3. 4. 5.] float32
[b'1' b'2' b'3' b'4' b'5'] |S1
[1 2 3 4 5] int8


In [8]:
print("We can also make a function to change data_types as:\n")
new=np.float32(arr3)
print(new)
print(new.dtype)

x=np.int_(new)
print(x)
print(x.dtype)

We can also make a function to change data_types as:

[1. 2. 3. 4. 5.]
float32
[1 2 3 4 5]
int32


In [9]:
y=x.astype(float)
print(y)

[1. 2. 3. 4. 5.]
