Dimensions in Numpy array

In [1]:
import numpy as np

x=[1,2,3,4,5]
y=np.array(x)
print(y)

[1 2 3 4 5]


# One Dimension

In [2]:
oneD_arry=np.array([1,2,3,4,5,6])
oneD_arry

array([1, 2, 3, 4, 5, 6])

In [3]:
print(oneD_arry.ndim)#tell us dimension

1


# Two Dimension

In [4]:
TwoD_array=np.array([[1,2,3,4,5],[6,7,8,9,10],[1,4,3,5,6]])
TwoD_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 1,  4,  3,  5,  6]])

In [5]:
print(TwoD_array.ndim)#tell us dimension

2


# Three Dimension

In [6]:
theeD_array=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
theeD_array

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [7]:
theeD_array.ndim#tell us dimension

3

# N_Dimension array

In [8]:
N_D_array=np.array([1,2,3],ndmin=10)
print(N_D_array)

[[[[[[[[[[1 2 3]]]]]]]]]]


In [9]:
print(N_D_array.ndim)#tell us dimension

10
