`Filter,Shuffle,Resize of an Array`

Filter

In [1]:
import numpy as np
arr=np.array(['s','a','b','c'])
f=[False,True,False,True]
new=arr[f]
print(new)

['a' 'c']


Shuffle 

In [2]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
np.random.shuffle(arr)
print(arr)

[1 7 5 4 2 6 3 8]


Unique

In [3]:
arr2=np.array([1,2,1,3,2,4,5,6,4,2])
# x=np.unique(arr2)
x=np.unique(arr2,return_index=True,return_counts=True)
print(x)

(array([1, 2, 3, 4, 5, 6]), array([0, 1, 3, 5, 6, 7], dtype=int64), array([2, 3, 1, 2, 1, 1], dtype=int64))


Resize

In [4]:
arr3=np.array([1,2,3,4,5,6])
# x=np.resize(arr,(3,2))
# print(x)

x=np.resize(arr,(2,3))
print(x)
print()
print(x.flatten(order="F"))
print(np.ravel(x,order='F'))

[[1 7 5]
 [4 2 6]]

[1 4 7 2 5 6]
[1 4 7 2 5 6]


In [5]:
var=np.array([[1,2,3],[4,5,6]])
print(var.flatten())
print(np.ravel(var))

[1 2 3 4 5 6]
[1 2 3 4 5 6]
